package io.github.ninbyo02.lami.ui.screens.settings

internal data class AnimationSelectionState(
    val selectedAnimation: AnimationType,
    val animationOptions: List<AnimationType>,
    val onSelectedAnimationChange: (AnimationType) -> Unit,
)

internal data class BaseAnimationUiState(
    val frameInput: String,
    val onFrameInputChange: (String) -> Unit,
    val intervalInput: String,
    val onIntervalInputChange: (String) -> Unit,
    val framesError: String?,
    val intervalError: String?,
    val summary: AnimationSummary,
)

internal data class InsertionAnimationUiState(
    val pattern1FramesInput: String,
    val onPattern1FramesInputChange: (String) -> Unit,
    val pattern1WeightInput: String,
    val onPattern1WeightInputChange: (String) -> Unit,
    val pattern1IntervalInput: String,
    val onPattern1IntervalInputChange: (String) -> Unit,
    val pattern2FramesInput: String,
    val onPattern2FramesInputChange: (String) -> Unit,
    val pattern2WeightInput: String,
    val onPattern2WeightInputChange: (String) -> Unit,
    val pattern2IntervalInput: String,
    val onPattern2IntervalInputChange: (String) -> Unit,
    val intervalInput: String,
    val onIntervalInputChange: (String) -> Unit,
    val everyNInput: String,
    val onEveryNInputChange: (String) -> Unit,
    val probabilityInput: String,
    val onProbabilityInputChange: (String) -> Unit,
    val cooldownInput: String,
    val onCooldownInputChange: (String) -> Unit,
    val enabled: Boolean,
    val onEnabledChange: (Boolean) -> Unit,
    val exclusive: Boolean,
    val onExclusiveChange: (Boolean) -> Unit,
    val pattern1FramesError: String?,
    val pattern1WeightError: String?,
    val pattern1IntervalError: String?,
    val pattern2FramesError: String?,
    val pattern2WeightError: String?,
    val pattern2IntervalError: String?,
    val intervalError: String?,
    val everyNError: String?,
    val probabilityError: String?,
    val cooldownError: String?,
    val patterns: List<InsertionPattern>,
    val defaultIntervalMs: Int,
    val shouldShowDefaultInterval: Boolean,
    val defaults: InsertionAnimationSettings,
    val summary: AnimationSummary,
    val previewValues: InsertionPreviewValues,
)
