package io.github.ninbyo02.lami.ui.screens.home

data class AcceleratorProbeSnapshot(
    val deviceManufacturer: String?,
    val deviceModel: String?,
    val deviceBoard: String?,
    val androidSdk: Int,
    val supportedAbis: List<String>,
    val cpuCoreCount: Int?,
    val cpuAbi: String?,
    val gpuVendor: String?,
    val gpuRenderer: String?,
    val gpuVersion: String?,
    val nnapiAvailable: Boolean,
    val nnapiDeprecatedWarning: Boolean,
    val nnapiDevices: List<String>,
    val probeSource: String,
    val probeError: String? = null,
    val gpuProbeSource: String? = null,
    val gpuProbeError: String? = null,
    val delegateProbeSource: String? = null,
    val delegateProbeError: String? = null,
    val delegateOptionCandidates: List<String> = emptyList(),
    val delegateBackendCandidates: List<String> = emptyList(),
    val delegateBackendEnumValues: List<String> = emptyList(),
    val delegateBackendEnumProbeError: String? = null,
    val delegatePreferredBackendSignatures: List<String> = emptyList(),
    val delegatePreferredBackendSignatureProbeError: String? = null,
    val delegateClassCandidates: List<String> = emptyList(),
    val delegateSwitchingSupportedHint: String? = null,
    val npuDelegateCandidates: List<String> = emptyList(),
    val npuBackendCandidates: List<String> = emptyList(),
    val backendNpuClassCandidates: List<String> = emptyList(),
    val backendNpuMethodCandidates: List<String> = emptyList(),
    val backendNpuConstructorSignatures: List<String> = emptyList(),
    val backendNpuNativeLibraryDirRequired: String? = null,
    val backendNpuProbeHint: String? = null,
    val backendNpuProbeError: String? = null,
    val npuStageProbeSource: String? = null,
    val npuConstructorAvailable: Boolean = false,
    val npuStringConstructorAvailable: Boolean = false,
    val npuNativeLibraryDirCandidate: String? = null,
    val npuStageProbeResult: String? = null,
    val npuStageProbeError: String? = null,
    val npuSocManufacturer: String? = null,
    val npuSocModel: String? = null,
    val npuOfficialVendor: String? = null,
    val npuOfficialSocSupport: String? = null,
    val npuModelRequirement: String? = null,
    val npuRuntimeLibraryRequirement: String? = null,
    val npuDispatchLibraryRequirement: String? = null,
    val npuCliProofRequirement: String? = null,
    val npuReadinessSummary: String? = null,
    val npuNativeLibraryDir: String? = null,
    val npuPackagedLibraryCandidates: List<String> = emptyList(),
    val npuVendorRuntimeLibraryStatus: String? = null,
    val npuDispatchLibraryStatus: String? = null,
    val qnnNpuAttemptRequested: String? = null,
    val qnnNpuAttempted: Boolean = false,
    val qnnNpuAvailable: String? = null,
    val qnnNpuSelectedPath: String? = null,
    val qnnNpuFallbackPath: String? = null,
    val qnnNpuAttemptStage: String? = null,
    val qnnNpuAttemptErrorClass: String? = null,
    val qnnNpuAttemptErrorMessage: String? = null,
    val qnnNpuAttemptEvidence: List<String> = emptyList(),
    val qnnDelegateCandidates: List<String> = emptyList(),
    val nnapiDelegateCandidates: List<String> = emptyList(),
    val npuProbeHint: String? = null,
    val npuProbeError: String? = null,
    val externalQairtStagePath: String = "/data/local/tmp/qairt",
    val externalQairtStageStatus: String = "unknown",
    val externalQairtQnnNetRunStatus: String = "unknown",
    val externalQairtQnnPlatformValidatorStatus: String = "unknown",
    val externalQairtQnnSdkVersion: String = "unknown",
    val externalQairtGpuBackendStatus: String = "not_checked",
    val externalQairtDspCore: String = "unknown",
    val externalQairtDspBackendStatus: String = "not_checked",
    val externalQairtNote: String? = null,
    val inferredExecutionTarget: String? = null,
    val inferredExecutionConfidence: String? = null,
    val inferredExecutionReason: String? = null,
)
