package io.github.ninbyo02.lami.ui.screens.home

data class AcceleratorProbeSnapshot(
    val deviceManufacturer: String?,
    val deviceModel: String?,
    val deviceBoard: String?,
    val androidSdk: Int,
    val supportedAbis: List<String>,
    val cpuCoreCount: Int?,
    val cpuAbi: String?,
    val gpuVendor: String?,
    val gpuRenderer: String?,
    val gpuVersion: String?,
    val nnapiAvailable: Boolean,
    val nnapiDeprecatedWarning: Boolean,
    val nnapiDevices: List<String>,
    val probeSource: String,
    val probeError: String? = null,
    val gpuProbeSource: String? = null,
    val gpuProbeError: String? = null,
    val delegateProbeSource: String? = null,
    val delegateProbeError: String? = null,
    val delegateOptionCandidates: List<String> = emptyList(),
    val delegateBackendCandidates: List<String> = emptyList(),
    val delegateBackendEnumValues: List<String> = emptyList(),
    val delegateBackendEnumProbeError: String? = null,
    val delegatePreferredBackendSignatures: List<String> = emptyList(),
    val delegatePreferredBackendSignatureProbeError: String? = null,
    val delegateClassCandidates: List<String> = emptyList(),
    val delegateSwitchingSupportedHint: String? = null,
    val inferredExecutionTarget: String? = null,
    val inferredExecutionConfidence: String? = null,
    val inferredExecutionReason: String? = null,
)
