package io.github.ninbyo02.lami.ui.screens.home

import io.github.ninbyo02.lami.ui.components.LocalInferenceEngineState

internal data class LocalInferenceRunResult(
    val state: LocalInferenceEngineState,
    val response: String? = null,
    val trace: LocalInferenceTrace = LocalInferenceTrace(),
    val closeLifecycleSummary: RunCloseLifecycleSummary? = null,
    val runnerWhitespaceTraceText: String? = null,
)

internal enum class LocalStatsAvailability {
    AVAILABLE_NOW,
    DERIVABLE_NOW,
    API_CANDIDATE_ONLY,
    NOT_FOUND,
}

internal enum class LocalStreamingApiProbeResult {
    ASYNC_API_NOT_FOUND,
    LISTENER_API_NOT_FOUND,
    SESSION_API_NOT_FOUND,
    ASYNC_INVOKE_FAILED,
    LISTENER_INVOKE_FAILED,
    SESSION_CREATE_FAILED,
    ASYNC_INVOKE_SUCCEEDED,
    LISTENER_INVOKE_SUCCEEDED,
    SESSION_CREATE_SUCCEEDED,
}

internal data class LocalStatsCandidateProbe(
    val availability: LocalStatsAvailability,
    val signature: String? = null,
    val returnTypeName: String? = null,
    val valueSummary: String? = null,
)

internal data class LocalInferenceTrace(
    val createMethodSignature: String? = null,
    val optionsBuildPath: String? = null,
    val generateMethodSignature: String? = null,
    val streamingCandidateDetected: Boolean? = null,
    val localModelDisplayName: String? = null,
    val mediaPipeProbeModelPath: String? = null,
    val selectedLocalModelSlot: String? = null,
    val npuPreviewModelConfigured: Boolean? = null,
    val genericFallbackModelConfigured: Boolean? = null,
    val modelNameProbe: LocalStatsCandidateProbe = LocalStatsCandidateProbe(LocalStatsAvailability.NOT_FOUND),
    val finishReasonProbe: LocalStatsCandidateProbe = LocalStatsCandidateProbe(LocalStatsAvailability.NOT_FOUND),
    val outputTokenProbe: LocalStatsCandidateProbe = LocalStatsCandidateProbe(LocalStatsAvailability.NOT_FOUND),
    val loadTimeProbe: LocalStatsCandidateProbe = LocalStatsCandidateProbe(LocalStatsAvailability.NOT_FOUND),
    val wallClockLoadDurationNs: Long? = null,
    val wallClockTotalInferenceDurationNs: Long? = null,
    val localTraceStartElapsedRealtimeMs: Long? = null,
    val localTraceFirstResponseElapsedRealtimeMs: Long? = null,
    val localTraceCompletedElapsedRealtimeMs: Long? = null,
    val promptEvalTimeProbe: LocalStatsCandidateProbe = LocalStatsCandidateProbe(LocalStatsAvailability.NOT_FOUND),
    val evalTimeProbe: LocalStatsCandidateProbe = LocalStatsCandidateProbe(LocalStatsAvailability.NOT_FOUND),
    val firstTokenProbe: LocalStatsCandidateProbe = LocalStatsCandidateProbe(LocalStatsAvailability.NOT_FOUND),
    val estimatedTokenProbe: LocalStatsCandidateProbe = LocalStatsCandidateProbe(LocalStatsAvailability.NOT_FOUND),
    val asyncApiProbeResult: LocalStreamingApiProbeResult? = null,
    val asyncApiSignature: String? = null,
    val listenerApiProbeResult: LocalStreamingApiProbeResult? = null,
    val listenerApiSignature: String? = null,
    val sessionApiProbeResult: LocalStreamingApiProbeResult? = null,
    val sessionApiSignature: String? = null,
    val sessionGenerateSignature: String? = null,
    val sessionAsyncSignature: String? = null,
    val sessionStreamingSignature: String? = null,
    val sessionTokenSignature: String? = null,
    val sessionPromptTokens: Int? = null,
    val sessionResponseTokens: Int? = null,
    val sessionTotalTokens: Int? = null,
    val measuredTokenSnapshot: LocalInferenceMeasuredTokenSnapshot? = null,
    val sessionTokenProbeErrorStage: String? = null,
    val sessionTokenProbeErrorClassName: String? = null,
    val sessionListenerSignature: String? = null,
    val sessionLifecycleSignature: String? = null,
    val selectedAssistantResponseSource: String? = null,
    val selectedAssistantResponseHead: String? = null,
    val oneShotResponseHead: String? = null,
    val assistantUpdateCount: Int = 0,
    val streamedCharsPerSecond: Double? = null,
    val appendBatchSizeAvg: Double? = null,
    val appendEventsPerSecond: Double? = null,
    val composeRecomposeEstimate: Int? = null,
    val markdownRepairCount: Int? = null,
    val uiAppendDebounceMs: Long? = null,
    val firstNonEmptyAssistantChunkSeen: Boolean = false,
    val assistantStreamedToUi: Boolean = false,
    val realPartialReceived: Boolean = false,
    val realPartialChunkCount: Int = 0,
    val officialFlowAttempted: Boolean = false,
    val officialFlowUsed: Boolean = false,
    val officialFlowFallbackReason: String? = null,
    val officialConversationApiAvailable: Boolean? = null,
    val officialFlowChunkCount: Int = 0,
    val officialChunkCount: Int = 0,
    val officialChunkIntervalAvgMs: Double? = null,
    val officialChunkIntervalMaxMs: Long? = null,
    val officialChunkIntervalMinMs: Long? = null,
    val officialChunkFirstToLastMs: Long? = null,
    val officialChunkCharsAvg: Double? = null,
    val officialChunkCharsMax: Int? = null,
    val officialChunkCharsMin: Int? = null,
    val officialChunkEmptyCount: Int = 0,
    val officialChunkNonEmptyCount: Int = 0,
    val officialChunkEventsPerSecond: Double? = null,
    val officialChunkCharsPerSecond: Double? = null,
    val requestedPreferredBackend: String? = null,
    val appliedPreferredBackend: String? = null,
    val preferredBackendApplyResult: String? = null,
    val preferredBackendHookReached: Boolean? = null,
    val preferredBackendHookSource: String? = null,
    val preferredBackendApplyError: String? = null,
    val preferredBackendApplyBuilderClass: String? = null,
    val preferredBackendApplyMethodCandidates: List<String> = emptyList(),
    val preferredBackendApplyBackendEnumCandidates: List<String> = emptyList(),
    val preferredBackendApplyNotSupportedReason: String? = null,
    val heldEngineCreatePath: String? = null,
    val llmInferenceCreateMethod: String? = null,
    val optionsBuilderSource: String? = null,
    val preferredBackendHookEligible: Boolean? = null,
    val preferredBackendHookMissingReason: String? = null,
    val preferredBackendRequiresEngineRecreate: Boolean? = null,
    val preferredBackendEngineRecreateReason: String? = null,
    val holderInstanceHash: Int? = null,
    val heldEngineHash: Int? = null,
    val holderAppInForeground: Boolean? = null,
    val holderLastAcquireAction: String? = null,
    val holderLastLifecycleEventReason: String? = null,
    val holderLastLifecycleDecisionAction: String? = null,
    val heldEngineRecreateRequestCount: Int? = null,
    val heldEngineWasPresentAtRunStart: Boolean? = null,
    val heldEngineCreatedDuringRun: Boolean? = null,
    val holderLastRecreateResult: String? = null,
    val holderLastRecreateReason: String? = null,
    val holderHasHeldEngineBeforeRecreate: Boolean? = null,
    val holderHasHeldEngineAfterRecreate: Boolean? = null,
    val heldEngineLifecycleHistory: String? = null,
    val heldEngineDestroyReason: String? = null,
    val heldEngineLastOwner: String? = null,
    val heldEngineLastFailureStage: String? = null,
    val heldEngineSnapshotBeforeDestroy: String? = null,
    val lastHeldEngineCreateReason: String? = null,
    val lastHeldEngineCreateSource: String? = null,
    val lastHeldEngineCreateAtElapsedMs: Long? = null,
    val lastHeldEngineCreateRequestedPreferredBackend: String? = null,
    val lastHeldEngineCreateStackHint: String? = null,
    val realPartialHookAttempted: Boolean = false,
    val realPartialHookAttached: Boolean = false,
    val realPartialCallbackCount: Int = 0,
    val localFailureDiagnosticsText: String? = null,
    val memorySnapshots: List<MemorySnapshot> = emptyList(),
    val safetyGuardBlock: SafetyGuardConversationBlock? = null,
)
