#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT_DIR="$ROOT_DIR/scripts"
# shellcheck source=scripts/lib_diagnostics_key_parser.sh
source "$SCRIPT_DIR/lib_diagnostics_key_parser.sh"

DEVICE_RUNS="$ROOT_DIR/artifacts/device_runs"
QUALITY_MATRIX="$ROOT_DIR/artifacts/gpu_output_quality_matrix"
APK_NATIVE_DIFF="$ROOT_DIR/artifacts/apk_native_diff"
OUTPUT="$ROOT_DIR/artifacts/gpu_investigation_report/GPU_INVESTIGATION_REPORT.md"

usage() {
  cat <<'USAGE'
Usage:
  scripts/render_gpu_investigation_report.sh \
    [--device-runs DIR] \
    [--quality-matrix DIR] \
    [--apk-native-diff DIR] \
    [--output FILE]

  scripts/render_gpu_investigation_report.sh --self-test

Renders a single Markdown report from copied device diagnostics and static
investigation artifacts. Missing inputs are recorded in the report and are not
fatal.
USAGE
}

latest_file_in_dir() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  find "$dir" -type f \
    ! -name 'GPU_CORRUPTION_REGRESSION_SUMMARY.md' \
    ! -name 'GPU_INVESTIGATION_REPORT.md' \
    -printf '%T@ %p\n' 2>/dev/null |
    sort -nr |
    awk 'NR == 1 { $1 = ""; sub(/^ /, ""); print; exit }'
}

first_file_with_key() {
  local dir="$1"
  local key="$2"
  [[ -d "$dir" ]] || return 0
  find "$dir" -type f 2>/dev/null |
    sort |
    while IFS= read -r file; do
      if grep -Eq "(^|[[:space:]])${key}=" "$file" 2>/dev/null; then
        printf '%s\n' "$file"
        return 0
      fi
    done
}

append_key_table() {
  local out="$1"
  local file="$2"
  shift 2
  local key value
  {
    printf '| Key | Value |\n'
    printf '| --- | --- |\n'
    for key in "$@"; do
      value="$(diagnostic_get_key_or_unavailable "$file" "$key")"
      printf '| `%s` | `%s` |\n' "$key" "$value"
    done
  } >>"$out"
}

append_file_or_missing() {
  local out="$1"
  local title="$2"
  local file="$3"
  local max_lines="${4:-120}"
  {
    printf '### %s\n\n' "$title"
    if [[ -f "$file" ]]; then
      printf 'Source: `%s`\n\n' "$file"
      printf '```text\n'
      sed -n "1,${max_lines}p" "$file"
      printf '```\n\n'
    else
      printf 'missing: `%s`\n\n' "$file"
    fi
  } >>"$out"
}

capture_command() {
  local out_file="$1"
  shift
  if "$@" >"$out_file" 2>&1; then
    return 0
  fi
  {
    printf 'COMMAND_FAILED=true\n'
    printf 'COMMAND='
    printf '%q ' "$@"
    printf '\n'
  } >>"$out_file"
  return 0
}

promotion_blocker_from_file() {
  local file="$1"
  [[ -f "$file" ]] || {
    printf 'unknown\n'
    return
  }
  local blocker quality gate callback_stage source_stage
  blocker="$(diagnostic_get_key_or_unavailable "$file" "gpu_output_quality_promotion_blocker")"
  quality="$(diagnostic_get_key_or_unavailable "$file" "gpu_output_quality_candidate_result")"
  gate="$(diagnostic_get_key_or_unavailable "$file" "gpu_output_quality_gate_status")"
  callback_stage="$(diagnostic_get_key_or_unavailable "$file" "callback_corruption_earliest_stage")"
  source_stage="$(diagnostic_get_key_or_unavailable "$file" "gpu_output_source_corruption_stage")"
  if [[ "$blocker" == "true" ||
    "$quality" == "quality_candidate_fail" ||
    "$gate" == "fail" ||
    "$callback_stage" == "raw_callback" ||
    "$source_stage" == "raw_callback" ]]; then
    printf 'true\n'
  elif [[ "$blocker" == "false" || "$quality" == "quality_candidate_pass" || "$gate" == "pass" ]]; then
    printf 'false\n'
  else
    printf 'unknown\n'
  fi
}

render_report() {
  local device_runs="$1"
  local quality_matrix="$2"
  local apk_native_diff="$3"
  local output="$4"
  local tmpdir latest_device executor_file promotion_blocker

  mkdir -p "$(dirname "$output")"
  tmpdir="$(mktemp -d)"
  REPORT_TMPDIR="$tmpdir"
  trap 'rm -rf "${REPORT_TMPDIR:-}"' RETURN

  latest_device="$(latest_file_in_dir "$device_runs" || true)"
  executor_file="$(first_file_with_key "$device_runs" "edge_gallery_executor_probe_result" || true)"
  [[ -n "$executor_file" ]] || executor_file="$latest_device"
  promotion_blocker="$(promotion_blocker_from_file "$latest_device")"

  {
    printf '# GPU Investigation Report\n\n'
    printf 'Generated by `scripts/render_gpu_investigation_report.sh`.\n\n'
    printf '## Overview\n\n'
    printf '| Input | Status | Path |\n'
    printf '| --- | --- | --- |\n'
    printf '| device runs | %s | `%s` |\n' "$([[ -d "$device_runs" ]] && printf present || printf missing)" "$device_runs"
    printf '| quality matrix | %s | `%s` |\n' "$([[ -d "$quality_matrix" ]] && printf present || printf missing)" "$quality_matrix"
    printf '| APK native diff | %s | `%s` |\n' "$([[ -d "$apk_native_diff" ]] && printf present || printf missing)" "$apk_native_diff"
    printf '| latest device run | %s | `%s` |\n' "$([[ -n "$latest_device" ]] && printf present || printf missing)" "${latest_device:-none}"
    printf '| executor probe file | %s | `%s` |\n\n' "$([[ -n "$executor_file" ]] && printf present || printf missing)" "${executor_file:-none}"
  } >"$output"

  {
    printf '## Latest Device Run Summary\n\n'
    if [[ -n "$latest_device" && -f "$latest_device" ]]; then
      printf 'Source: `%s`\n\n' "$latest_device"
    else
      printf 'missing: no device run diagnostics found.\n\n'
    fi
  } >>"$output"
  if [[ -n "$latest_device" && -f "$latest_device" ]]; then
    append_key_table "$output" "$latest_device" \
      selected_backend route_family status failure_stage \
      callback_corruption_earliest_stage gpu_output_source_corruption_stage \
      gpu_output_quality_candidate_result gpu_output_quality_gate_status \
      gpu_output_quality_promotion_blocker gpu_sampler_root_cause_candidate \
      gpu_fragmentation_score callback_quality_classification
    printf '\n' >>"$output"
  fi

  {
    printf '## GPU Output Quality Summary\n\n'
    if [[ -d "$quality_matrix" && -x "$SCRIPT_DIR/summarize_gpu_output_quality_matrix.sh" ]]; then
      capture_command "$tmpdir/quality_matrix.txt" "$SCRIPT_DIR/summarize_gpu_output_quality_matrix.sh" --input "$quality_matrix"
      printf '```text\n'
      cat "$tmpdir/quality_matrix.txt"
      printf '```\n\n'
    else
      printf 'missing: `%s`\n\n' "$quality_matrix"
    fi
  } >>"$output"

  {
    printf '## Executor Probe Classification\n\n'
    if [[ -n "$executor_file" && -f "$executor_file" && -x "$SCRIPT_DIR/classify_gpu_executor_probe_result.sh" ]]; then
      capture_command "$tmpdir/executor_classification.txt" "$SCRIPT_DIR/classify_gpu_executor_probe_result.sh" --input "$executor_file"
      printf 'Source: `%s`\n\n' "$executor_file"
      printf '```text\n'
      cat "$tmpdir/executor_classification.txt"
      printf '```\n\n'
    else
      printf 'missing: no executor probe diagnostics found.\n\n'
    fi
  } >>"$output"

  {
    printf '## Runtime/Native Stack Fingerprint Summary\n\n'
  } >>"$output"
  append_file_or_missing "$output" "native_stack_fingerprint.txt" "$apk_native_diff/native_stack_fingerprint.txt" 120

  {
    printf '## APK Native Diff Summary\n\n'
  } >>"$output"
  append_file_or_missing "$output" "runtime_stack_summary.txt" "$apk_native_diff/runtime_stack_summary.txt" 120
  append_file_or_missing "$output" "native_lib_inventory.tsv" "$apk_native_diff/native_lib_inventory.tsv" 80
  append_file_or_missing "$output" "jni_symbol_diff.tsv" "$apk_native_diff/jni_symbol_diff.tsv" 80

  {
    printf '## Regression Suite Summary\n\n'
    if [[ -d "$device_runs" && -x "$SCRIPT_DIR/summarize_gpu_regression_results.sh" ]]; then
      capture_command "$tmpdir/regression_stdout.txt" "$SCRIPT_DIR/summarize_gpu_regression_results.sh" --input "$device_runs" --output "$tmpdir/GPU_CORRUPTION_REGRESSION_SUMMARY.md"
      if [[ -f "$tmpdir/GPU_CORRUPTION_REGRESSION_SUMMARY.md" ]]; then
        cat "$tmpdir/GPU_CORRUPTION_REGRESSION_SUMMARY.md"
        printf '\n'
      else
        printf '```text\n'
        cat "$tmpdir/regression_stdout.txt"
        printf '```\n\n'
      fi
    else
      printf 'missing: `%s`\n\n' "$device_runs"
    fi
  } >>"$output"

  {
    printf '## Promotion Blocker Status\n\n'
    printf '| Signal | Value |\n'
    printf '| --- | --- |\n'
    printf '| promotion_blocker_from_latest_device_run | `%s` |\n' "$promotion_blocker"
    if [[ -n "$latest_device" && -f "$latest_device" ]]; then
      printf '| gpu_output_quality_candidate_result | `%s` |\n' "$(diagnostic_get_key_or_unavailable "$latest_device" gpu_output_quality_candidate_result)"
      printf '| callback_corruption_earliest_stage | `%s` |\n' "$(diagnostic_get_key_or_unavailable "$latest_device" callback_corruption_earliest_stage)"
      printf '| gpu_output_source_corruption_stage | `%s` |\n' "$(diagnostic_get_key_or_unavailable "$latest_device" gpu_output_source_corruption_stage)"
      printf '| gpu_sampler_root_cause_candidate | `%s` |\n' "$(diagnostic_get_key_or_unavailable "$latest_device" gpu_sampler_root_cause_candidate)"
    fi
    printf '\n'
    if [[ "$promotion_blocker" == "true" ]]; then
      printf 'Status: **blocked**. Keep standard GPU promotion disabled.\n\n'
    elif [[ "$promotion_blocker" == "false" ]]; then
      printf 'Status: **not blocked by latest run**. Repeat stability and quality suite before changing any promotion gate.\n\n'
    else
      printf 'Status: **unknown**. Missing diagnostics; do not promote.\n\n'
    fi
  } >>"$output"

  cat >>"$output" <<'MARKDOWN'
## Root Cause Ranking

| Rank | Candidate | Current confidence |
| ---: | --- | ---: |
| 1 | GPU_ARTISAN / internal executor selection mismatch | 72% |
| 2 | hidden RuntimeConfig / backend constraint / preferred engine type difference | 66% |
| 3 | GPU KV cache / decode cache path difference | 56% |
| 4 | native runtime stack difference | 46% |
| 5 | callback semantics / hidden aggregation layer | 28% |
| 6 | sampler setting difference | 18% |
| 7 | maxTokens / cacheDir / public ConversationConfig difference | 16% |
| 8 | model file difference | 8% |

## Next Actions

1. If `Promotion Blocker Status` is blocked, do not promote standard GPU.
2. If executor probe classification says `same_stack_different_executor`, focus on internal executor/backend selection evidence.
3. If APK native diff says runtime stack differs, compare target library SHA-256 values before any further runtime experiment.
4. If regression summary says `gpu_only_corrupt` or `long_text_only_corrupt`, collect raw callback artifacts for those prompts.
5. If quality passes in one run, repeat app restart, short/medium/long, Markdown, mixed-language, and multi-turn tests before any Phase 2 discussion.
MARKDOWN

  printf 'Wrote GPU investigation report to: %s\n' "$output"
}

run_self_test() {
  local tmpdir
  tmpdir="$(mktemp -d)"
  SELF_TEST_TMPDIR="$tmpdir"
  trap 'rm -rf "${SELF_TEST_TMPDIR:-}"' EXIT

  mkdir -p "$tmpdir/device_runs" "$tmpdir/quality_matrix" "$tmpdir/apk_native_diff"
  cat >"$tmpdir/device_runs/gpu_executor_probe.txt" <<'EOF'
selected_backend=GPU route_family=local_gpu status=success edge_gallery_executor_probe_result=same_sampler_different_executor executor_selection_fingerprint=execB loaded_native_runtime_stack_fingerprint=stackA gpu_output_quality_candidate_result=quality_candidate_fail callback_corruption_earliest_stage=raw_callback gpu_output_source_corruption_stage=raw_callback gpu_sampler_root_cause_candidate=runtime_decode_fragmentation gpu_output_quality_gate_status=fail gpu_output_quality_promotion_blocker=true gpu_fragmentation_score=0.812 callback_quality_classification=severe_fragmentation
EOF
  cat >"$tmpdir/quality_matrix/baseline.txt" <<'EOF'
gpu_output_quality_matrix_mode=baseline gpu_output_quality_candidate_result=quality_candidate_fail gpu_fragmentation_score=0.812 average_chunk_length=1.7 one_char_chunk_ratio=0.52 gpu_output_suspicious_fragment_tail_ratio=0.18 gpu_sampler_root_cause_candidate=runtime_decode_fragmentation
EOF
  cat >"$tmpdir/apk_native_diff/runtime_stack_summary.txt" <<'EOF'
runtime_stack_same=no
jni_surface_same=yes
executor_symbol_same=no
EOF
  cat >"$tmpdir/apk_native_diff/native_stack_fingerprint.txt" <<'EOF'
EDGE_RUNTIME_STACK_FINGERPRINT=edge
LAMI_RUNTIME_STACK_FINGERPRINT=lami
EOF
  cat >"$tmpdir/apk_native_diff/native_lib_inventory.tsv" <<'EOF'
library	edge_present	edge_size	edge_sha256	lami_present	lami_size	lami_sha256	same_sha256
libLiteRt.so	yes	10	edge	yes	10	lami	no
EOF
  cat >"$tmpdir/apk_native_diff/jni_symbol_diff.tsv" <<'EOF'
symbol	edge_present	lami_present
nativeGenerateContent	yes	yes
EOF

  render_report "$tmpdir/device_runs" "$tmpdir/quality_matrix" "$tmpdir/apk_native_diff" "$tmpdir/report.md" >/tmp/lami_gpu_report_self_test.out
  grep -Fq '## Overview' "$tmpdir/report.md" || {
    echo "self-test failed: missing Overview" >&2
    exit 1
  }
  grep -Fq '## Promotion Blocker Status' "$tmpdir/report.md" || {
    echo "self-test failed: missing Promotion Blocker Status" >&2
    exit 1
  }
  grep -Fq 'Status: **blocked**' "$tmpdir/report.md" || {
    echo "self-test failed: expected blocked status" >&2
    exit 1
  }

  render_report "$tmpdir/missing_device" "$tmpdir/missing_quality" "$tmpdir/missing_apk" "$tmpdir/missing_report.md" >/tmp/lami_gpu_report_missing_self_test.out
  grep -Fq 'missing' "$tmpdir/missing_report.md" || {
    echo "self-test failed: missing-input report did not record missing inputs" >&2
    exit 1
  }

  rm -rf "$tmpdir"
  SELF_TEST_TMPDIR=""
  trap - EXIT
  echo "SELF_TEST=pass"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --device-runs)
      DEVICE_RUNS="${2:?missing --device-runs value}"
      shift 2
      ;;
    --quality-matrix)
      QUALITY_MATRIX="${2:?missing --quality-matrix value}"
      shift 2
      ;;
    --apk-native-diff)
      APK_NATIVE_DIFF="${2:?missing --apk-native-diff value}"
      shift 2
      ;;
    --output)
      OUTPUT="${2:?missing --output value}"
      shift 2
      ;;
    --self-test)
      run_self_test
      exit 0
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

render_report "$DEVICE_RUNS" "$QUALITY_MATRIX" "$APK_NATIVE_DIFF" "$OUTPUT"
